apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
    service: helloworld
    infra: minikube
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: helloworld
