apiVersion: v1
data:
  tls.crt: |-
   {{quote .Values.tlscrt | toYaml | b64enc }}
  tls.key: |-
   {{quote .Values.tlskey | toYaml | b64enc }}
kind: Secret
metadata:
  name: "{{.Values.name}}"
  namespace: "{{.Values.namespace}}"
type: kubernetes.io/tls