apiVersion: v1
data:
  tls.crt: |-
   {{tpl(.Values.tlscrt) . | b64enc | quote}}
  tls.key: |-
   {{tpl(.Values.tlskey) . | b64enc | quote}}
kind: Secret
metadata:
  name: "{{.Values.name}}"
  namespace: "{{.Values.namespace}}"
type: kubernetes.io/tls