apiVersion: v1
data:
  tls.crt: |-
   {{.Values.tlscrt | toYaml | b64enc | quote}}
  tls.key: |-
   {{.Values.tlskey | toYaml | b64enc | quote}}
kind: Secret
metadata:
  name: "{{.Values.name}}"
  namespace: "{{.Values.namespace}}"
type: kubernetes.io/tls