---
name: <+pipeline.variables.name>
namespace: <+infra.namespace>
tlscrt: <+pipeline.stages.istiotlssecret.spec.execution.steps.converttobase64.output.outputVariables.tlscertificatecertbase64>
tlskey: <+pipeline.stages.istiotlssecret.spec.execution.steps.converttobase64.output.outputVariables.tlscertificatekeybase64>
---